# Generated by Django 4.0.4 on 2022-04-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('item_url', models.URLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '中古PC',
                'verbose_name_plural': '中古PC',
            },
        ),
    ]
