# Generated by Django 4.0.4 on 2022-04-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedpc',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usedpc',
            name='img1',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='img2',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='img3',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='img4',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='img5',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='スペック詳細',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedpc',
            name='メーカー',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedpc',
            name='画面サイズ',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedpc',
            name='記憶容量',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
