# Generated by Django 4.0.4 on 2022-04-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0002_remove_usedpc_created_at_usedpc_img1_usedpc_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedpc',
            name='モニタタイプ',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
