# Generated by Django 4.0.4 on 2022-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0004_usedpc_モニタサイズ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedpc',
            name='item_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usedpc',
            name='スペック詳細',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='usedpc',
            name='メーカー',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usedpc',
            name='画面サイズ',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usedpc',
            name='記憶容量',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
