# Generated by Django 4.0.4 on 2022-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0005_alter_usedpc_item_id_alter_usedpc_スペック詳細_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedpc',
            name='OS',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
