# Generated by Django 4.0.4 on 2022-04-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0007_usedpc_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_url', models.URLField()),
                ('img1', models.URLField(blank=True, default='', null=True)),
                ('img2', models.URLField(blank=True, default='', null=True)),
                ('img3', models.URLField(blank=True, default='', null=True)),
                ('img4', models.URLField(blank=True, default='', null=True)),
                ('img5', models.URLField(blank=True, default='', null=True)),
                ('CPU', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('CPUスコア', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('画面サイズ', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('画面種類', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('解像度', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('タッチパネル', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('in1タイプ', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ワイド画面', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('表面処理', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('メモリ容量', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('メモリ規格', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('メモリスロット空き', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ストレージ容量', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('HDD回転数', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('OS', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Office詳細', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ドライブ規格', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ビデオチップ', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ビデオメモリ', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('駆動時間', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('インターフェース', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('インテルEvoプラットフォーム', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ゲーミングPC', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('USBPD', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ファンレス', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('生体認証', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('センサー', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('BTO対応', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('その他', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('無線LAN', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('WiFiDirect対応', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('NFC', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('LAN', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('SIMフリー対応', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('SIMカード', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('地上デジタルチューナー', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('重量', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('幅x高さx奥行', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('エコマーク', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('認定番号', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('カラー', models.URLField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': '新品PC',
                'verbose_name_plural': '新品PC',
            },
        ),
    ]
