# Generated by Django 4.0.4 on 2022-04-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0009_rename_item_id_newpc_title_remove_newpc_item_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpc',
            name='img6',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='img6',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
