# Generated by Django 4.0.4 on 2022-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0011_sp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp',
            name='製品名',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
