# Generated by Django 4.0.4 on 2022-04-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0013_newpc_os種類'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpc',
            name='ネットワーク接続タイプ',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
