# Generated by Django 4.0.4 on 2022-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0015_newpc_メモリ'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpc',
            name='コア数',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
