# Generated by Django 4.0.4 on 2022-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0016_newpc_コア数'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpc',
            name='防水機能',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
