# Generated by Django 4.0.4 on 2022-04-26 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakaku_django_app', '0018_newpc_防塵機能'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpc',
            name='タッチペン付属',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usedpc',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=''),
        ),
    ]
